config:
  backup: true
  create: true
  dotpath: src
dotfiles:
  d_colors:
    dst: ~/.vim/colors
    src: vim/colors
  d_qutebrowser:
    dst: ~/.config/qutebrowser
    src: config/qutebrowser
  f_adjust_brightness.py:
    dst: ~/bin/adjust_brightness.py
    src: bin/adjust_brightness.py
  f_aliases:
    dst: ~/.aliases
    src: aliases
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gtk3.0_config:
    dst: ~/.config/gtk-3.0/settings.ini
    src: config/gtk-3.0/settings.ini
  f_gtkrc-2.0:
    dst: ~/.gtkrc-2.0
    src: gtkrc-2.0
  f_i3_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_i3blocks_desktop:
    dst: ~/.config/i3/i3blocks.conf
    src: config/i3/i3blocks.conf
  f_init.el:
    dst: ~/.emacs.d/init.el
    src: emacs.d/init.el
  f_launch.sh:
    dst: ~/.config/polybar/launch.sh
    src: config/polybar/launch.sh
  f_makepkg.conf:
    dst: /etc/makepkg.conf
    src: etc/makepkg.conf
  f_mpd.conf:
    dst: ~/.config/mpd/mpd.conf
    src: config/mpd/mpd.conf
  f_ncmpcpp_config:
    dst: ~/.ncmpcpp/config
    src: ncmpcpp/config
  f_nvimrc:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_pacman.conf:
    dst: /etc/pacman.conf
    src: etc/pacman.conf
  f_pavolume.sh:
    dst: ~/.config/polybar/pavolume.sh
    src: config/polybar/pavolume.sh
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_ranger_rc.conf:
    dst: ~/.config/ranger/rc.conf
    src: config/ranger/rc.conf
  f_ranger_scope.sh:
    dst: ~/.config/ranger/scope.sh
    src: config/ranger/scope.sh
  f_suspend@.service:
    dst: /etc/systemd/system/suspend@.service
    src: etc/systemd/system/suspend@.service
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_ycm_extra_conf.py:
    dst: ~/.vim/.ycm_extra_conf.py
    src: vim/.ycm_extra_conf.py
  f_zprofile:
    dst: ~/.zprofile
    src: zprofile
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  arch-desktop:
  - f_xinitrc
  - f_nvimrc
  - f_vimrc
  - f_xresources
  - f_zshrc
  - f_zprofile
  - f_gtkrc-2.0
  - f_gitconfig
  - f_bashrc
  - f_aliases
  - f_gtk3.0_config
  - f_i3_config
  - f_i3blocks_desktop
  - f_termite_config
  - f_ranger_rc.conf
  - f_ranger_scope.sh
  - f_init.el
  think470:
  - f_xinitrc
  - f_nvimrc
  - f_vimrc
  - f_xresources
  - f_zshrc
  - f_zprofile
  - f_gtkrc-2.0
  - f_gitconfig
  - f_adjust_brightness.py
  - f_bashrc
  - f_aliases
  - f_gtk3.0_config
  - f_i3_config
  - f_termite_config
  - f_ranger_rc.conf
  - f_ranger_scope.sh
  - f_suspend@.service
  - f_makepkg.conf
  - f_pacman.conf
  - f_polybar_config
  - f_launch.sh
  - f_pavolume.sh
  - f_tmux.conf
  - f_ncmpcpp_config
  - f_mpd.conf
  - d_colors
  - f_ycm_extra_conf.py
  - f_init.el
  - d_qutebrowser
