#
# ~/.xinitrc
#

# Disable mouse acceleration
xset m 0 0

{%@@ if profile == "arch-desktop" @@%}
# Set screen resolutions
setres --port HDMI-1 1920 1080
setres --port DVI-I-1 1280 1024
bash ~/.screenlayout/screen.sh
{%@@ endif @@%}

# Set wallpaper
feh --bg-scale $HOME/Pictures/wallpaper

# Set keyboard layout
setxkbmap de,de

# Remap Capslock to escape
setxkbmap -option caps:escape

{%@@ if profile == "think470" @@%}
# Start compton in background
compton -b

# Setup xautolock
xautolock -time 5 -locker "i3lock-fancy -p -- scrot -z" &
{%@@ endif @@%}

# Start caffeine (systray) in background
caffeine &

# Run i3wm
exec i3
